apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jazu2refo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jazu2refo-go 
  name: jazu2refo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jazu2refo-go 
